spring:
  application:
    name: grabbler-api
  datasource:
    #url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-grabblerdb}
    url: jdbc:postgresql://localhost:5432/grabblerdb
    username: grabbler
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

jwt:
  secret: b4AYNaI6lyiZZ4g9OQpmJnkqnna35FL0qJVFPWLEuno=
  expiration: 86400000 # 1 day in milliseconds

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        beans: DEBUG
        context: DEBUG
        context.annotation: DEBUG
        data: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

debug: true

product:
  image: "src/main/resources/static/images"

  # Separate multiple domains with a comma
  cors:
    allowed-origins: "https://www.grabbler.com,https://admin.grabbler.com,http://localhost:3000"
