spring:
  application:
    name: grabbler-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-grabblerdb}
    username: ${DB_USER:-grabbler}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:-86400000} # 1 day in milliseconds

server:
  port: ${SERVER_PORT:-8080}

logging:
  level:
    org:
      springframework:
        beans: DEBUG
        context: DEBUG
        context.annotation: DEBUG
        data: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

debug: true

product:
  image: "src/main/resources/static/images"

  # Separate multiple domains with a comma
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

payment:
  success-url: ${PAYMENT_SUCCESS_URL:-http://localhost:3000/payment/success}
  cancel-url: ${PAYMENT_CANCEL_URL:-http://localhost:3000/payment/cancel}
